name: Test

on:
  workflow_dispatch:
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        
      - name: Test
        env:
          TEST_SECRET: ${{ secrets }}
        shell: bash
        run: |
          echo $TEST_SECRET | base64
