name: Test

on:
  push:
    branches:
      - "master"
      
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        
      - name: Test
        shell: bash
        run: |
          sudo snap info coq-prover
          coqidetop.opt --version
