name: Test

on:
  push:
    branches:
      - "master"
      
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        
      - name: Install and configure ECS CLI
        shell: bash
        run: |
          snap --version
          
